name: Autopush main

on:
  push:
    branches:
      - release-autopush

jobs:
  autopush:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: release-autopush

      - name: Merge release-autopush into main
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout main
          git pull origin main
          git reset --hard origin/main
          git merge --ff-only release-autopush
          git push origin main


